### PR TITLE
Release 1.17.6

### PR DESCRIPTION
**Pull request by saig0**
## Description

Released new patch version 1.17.6. :building_construction: 

## Related issues

### CODE REVIEW

**Comment by vicmosin** [comment]
@saig0 I think something went wrong.. Updating to recent camunda 7.21 and providing the feel-engine 1.17.6 brings the following incompatibility issue

Bildschirmfoto 2024-04-24 um 08 39 14

**Comment by saig0** [comment]
@vicmosin thank you for reporting. :+1: This compiler issue seems to be related to the shaded JAR that bundles the Scala library. 

Can you share a repository to reproduce the issue?
Did it work with version 1.17.5?

**Comment by vicmosin** [comment]
I have no repository for this yet, but basically the builtin 1.17.5 (which is part of camunda-engine-dmn:7.21.0) compiles without any issue, but once I exclude it and provide the 1.17.6 (with the same camunda-engine-dmn:7.21.0) it starts to complain

**Comment by vicmosin** [comment]
@saig0 just making sure you got the last message :)

**Comment by saig0** [comment]
@vicmosin sounds like a dependency issue. Make sure to use the same versions. Maybe, a different Scala library is used from somewhere. Since the DMN uses the bundled JAR with the Scala library, use the bundled Scala classes should be used.

**Pull request merged**
