### PR TITLE
New temporal functions: now() + today()

### LINKED ISSUE #118: Add "current date" function
**Is your feature request related to a problem? Please describe.**
Hi, I need to calculate the age of a user based on its birthday using `zeebe-script-worker`. The problem is that I don't have the current date to subtract it from.

**Describe the solution you'd like**
I would like to have a function to get the current date, for example `date()`.

Thank you

### PR DESCRIPTION
**Pull request by saig0**
## Description

* new temporal functions `now()` and `today()`
* new SPI FeelEngineClock to access the current time
* using the system clock by default
* load clock via service loader for the script engine
* refactoring of the builtin-functions: split them into different classes

## Related issues

closes #118

### CODE REVIEW

**Comment by koevskinikola** [comment]
Hey @saig0,

Sorry for the delay, I was on vacation until today. 

I will review the PR by the end of this week (04.09.2020) since there are some higher priority topics I need to address first. If you would prefer to have the PR merged faster, please ping me or ask another developer.

Best,
Nikola

**Comment by saig0** [comment]
@koevskinikola welcome back :wave: 
I can wait a few days :wink: Thanks!

**Review by koevskinikola — APPROVED** [review]
Looks good!

@saig0  please rebase the branch before merging.

**Comment by falko** [comment]
@saig0 sounds like we would also like these FEEL functions to be included in DMN 1.4, right?

**Comment by saig0** [comment]
@falko definitely :+1: 
These functions are also supported by other vendors, like Drools.

**Pull request merged**
