### PR TITLE
feat: added weekday for date and datetime, issue #160

### LINKED ISSUE #160: I can access the weekday as property of a date/date-time
**Describe the bug**
I can not access the `weekday` property of a date/date-time value. 

**To Reproduce**
Expression `date("2018-12-10").weekday` fails to evaluate but should return `1`.

**Expected behavior**
A date/date-time value has a property `weekday`. The property is a number value `[1..7]` where `1` is Monday and `7` is Sunday.

**Environment**
* FEEL engine version: 1.11.2

### PR DESCRIPTION
**Pull request by kaaquist**
Signed-off-by: Kasper Aaquist Johansen <kasperaaquist@gmail.com>

## Description

* added the weekday Builtin function to date and datetime. 

closes #160

### CODE REVIEW

**Review by saig0 — CHANGES_REQUESTED** [review]
@kaaquist thank you for your contribution :cookie: 

In the specification, `weekday` is defined as a property of a date/date-time value. This is different to a built-in function. From the spec:

image

Currently, these properties are defined here: https://github.com/camunda/feel-scala/blob/master/src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala#L904-L992

**Comment by kaaquist** [comment]
Sorry about that. I will correct that.

**Comment by kaaquist** [comment]
I have corrected the mistake, and added the new implementation. 👍

**Review by saig0 — CHANGES_REQUESTED** [review]
Looks good. Thank you :cake: 

Please add the new property to the documentation here: https://github.com/camunda/feel-scala/blob/master/docs/develop/feel-expression.md#special-properties

**Review by saig0 — APPROVED** [review]
Super :tada:

**Pull request merged**
