### PR TITLE
chore(deps): update scala version to 2.13.1

### PR DESCRIPTION
**Pull request by tasso94**
related to CAM-11259

### CODE REVIEW

**Comment by saig0** [comment]
BTW: can we enable Dependabot for this repo?

**Comment by tasso94** [comment]
I've just enabled Depndabot. However, it seems like it does not work with sbt.

**Comment by saig0** [comment]
Thank you for enabling the bot :+1: 

Yes. SBT is currently not supported (https://github.com/dependabot/dependabot-core/issues/352). But the primary build tool is Maven, so that is a good improvement :tada: 
Let's keep this topic in mind :)

**Comment by tasso94** [comment]
@koevskinikola, it seems like `scala-parser-combinators_2.13` currently not compatible with Scala 2.13.1 (a warning is displayed). Let's don't merge this change for now.

**Comment by koevskinikola** [comment]
@tasso94 I will close this PR until the `scala-parser-combinators_2.13` becomes compatible with Scala `2.13.1`, at which point we can re-open it.

**Pull request closed without merging**
