### PR TITLE
fix(builtin-function): fix string conversion of years-months-durations

### LINKED ISSUE #631: String conversion of negative duration
**Describe the bug**
A negative duration is converted to a wrong format.

**To Reproduce**
```bash
Compiling /mnt/c/git/scala/feel-scala/feel-repl.sc
===== FEEL Engine REPL (1.11.2) ======
Evaluate FEEL expressions using 'feel("1 + 3")'
Evaluate FEEL unary-tests using 'unaryTests("[2..5]", 4)'
Provide variables as Map using 'feel("x + 3", Map("x" -> 2))'
Provide variables as JSON string using 'feel("x + 3", "{ \"x\" : 2 }")'
Welcome to the Ammonite Repl 2.4.0 (Scala 2.13.6 Java 18.0.1)
@ feel("string(duration(\"-P1Y\"))")
> P-1Y
```

**Expected behavior**
`-P1Y`
Related [test case](https://github.com/camunda/dmn-tck/blob/0b613499cd5fe5c49bd99e8c89dc6a13bc425adb/TestCases/non-compliant/0079-feel-string-function/0079-feel-string-function.dmn#L235) in the DMN TCK
```xml
    <decision name="ym_duration_002" id="_ym_duration_002">
        <description>Tests FEEL expression: 'string(duration("-P1Y"))' and expects result: '"-P1Y" (string)'</description>
        <question>Result of FEEL expression 'string(duration("-P1Y"))'?</question>
        <allowedAnswers>"-P1Y" (string)</allowedAnswers>
        <variable typeRef="string" name="ym_duration_002"/>
        <literalExpression>
            <text>string(duration("-P1Y"))</text>
        </literalExpression>
    </decision>
```
    

**Environment**
* FEEL engine version: > 1.11.2 (probably > 1.0.0)
* Affects: 
  * Camunda Platform ?
  * Zeebe broker: ?

### PR DESCRIPTION
**Pull request by sebi87**
## Description

* fix string conversion of years-months-durations
* add tests for string conversion of zero-length years-months-duration
* add tests for string conversion of negative years-months-duration

## Related issues

closes #631

### CODE REVIEW

**Comment by sebi87** [comment]
@saig0 The Clirr API check is failing at the moment. Do you have advice how to fix this or is it a false-positive?

**Comment by saig0** [comment]
@sebi87 I updated the Clirr config (https://github.com/camunda/feel-scala/pull/639). If you rebase, the build should pass now.

**Review by saig0 — APPROVED** [review]
@sebi87 very nice. :tada: Your PR is ready to merge. :rocket:

**Pull request merged**
